### ISSUE TITLE
Add optional sha256 and sha512 fields to validate recipe downloads

### ISSUE THREAD

**Issue by val-ms** [Cisco-Talos/Mussels#43]
Add optional sha256 and sha512 fields to validate recipe downloads. 
e.g.
```yaml
name: libbz2
version: "1.0.8"
url: https://sourceware.org/pub/bzip2/bzip2-1.0.8.tar.gz
sha512: "__________________some hash____________________"
type: recipe
mussels_version: "0.2"
platforms:
  Darwin:
...
```
